tables:
  products:
    columns:
      id: serial primary key
      base_price: numeric(10,2)
      tax_rate: numeric(4,2)
      tax_amount:
        definition: numeric(10,2)
        formula: "@base_price * @tax_rate"
      total_price:
        definition: numeric(10,2)
        formula: "@base_price + @tax_amount"
