version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: genlogic_test
      POSTGRES_USER: genlogic
      POSTGRES_PASSWORD: testpassword
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    command: postgres -c log_statement=all

volumes:
  postgres_test_data: