# COUNT Automation Example
# Automatically counts the number of child records

columns:
  id:
    type: integer
    sequence: true
    primary_key: true

tables:
  customers:
    columns:
      customer_id:
        $ref: id

      customer_name:
        type: varchar
        size: 100

      # Automatically counts the number of orders for this customer
      order_count:
        type: integer
        automation:
          type: COUNT
          table: orders
          foreign_key: customer_fk
          column: order_id  # Column to count (usually the primary key)

      # Can also count non-null values of a specific column
      paid_order_count:
        type: integer
        automation:
          type: COUNT
          table: orders
          foreign_key: customer_fk
          column: paid_amount  # Counts only orders where paid_amount IS NOT NULL

  orders:
    foreign_keys:
      customer_fk:
        table: customers

    columns:
      order_id:
        $ref: id

      order_total:
        type: numeric
        size: 10
        decimal: 2

      paid_amount:
        type: numeric
        size: 10
        decimal: 2
        # This can be NULL if order is unpaid

# How COUNT works:
# 1. INSERT new order with customer_fk=1
#    → customers.order_count for customer 1 increases by 1
#    → If paid_amount IS NOT NULL, customers.paid_order_count also increases by 1
# 2. UPDATE order SET paid_amount=100.00 WHERE paid_amount IS NULL
#    → customers.paid_order_count increases by 1 (NULL → NOT NULL transition)
# 3. UPDATE order SET paid_amount=NULL WHERE paid_amount IS NOT NULL
#    → customers.paid_order_count decreases by 1 (NOT NULL → NULL transition)
# 4. DELETE order
#    → Both counts decrease appropriately
#
# COUNT automation handles NULL transitions intelligently