# SUM Automation Example
# Automatically calculates the sum of child values in parent records

columns:
  id:
    type: integer
    sequence: true
    primary_key: true

  amount:
    type: numeric
    size: 10
    decimal: 2

tables:
  accounts:
    columns:
      account_id:
        $ref: id

      account_name:
        type: varchar
        size: 100

      # This balance automatically maintains the SUM of all transaction amounts
      balance:
        $ref: amount
        automation:
          type: SUM
          table: transactions      # Source table (child)
          foreign_key: account_fk  # FK in source table that points back to this table
          column: amount           # Column in source table to sum

  transactions:
    foreign_keys:
      account_fk:
        table: accounts

    columns:
      transaction_id:
        $ref: id

      amount: null  # This gets summed into accounts.balance

      description:
        type: varchar
        size: 200

# How it works:
# 1. When you INSERT into transactions with account_fk=1, amount=100.00
#    → accounts.balance for account 1 increases by 100.00
# 2. When you UPDATE transactions SET amount=150.00 WHERE transaction_id=1
#    → accounts.balance adjusts by +50.00 (incremental: 150.00 - 100.00)
# 3. When you DELETE transaction with amount=100.00
#    → accounts.balance decreases by 100.00
#
# The automation uses efficient triggers with OLD/NEW values for O(1) performance