tables:
  users:
    columns:
      id: integer primary key

  posts:
    columns:
      id: integer primary key
    foreign-keys:
      creator:
        table: users
        prefix: created
        suffix: by
