tables:
  a:
    columns:
      id: integer primary key
      b_id: integer
    foreign-keys:
      b: { table: b }

  b:
    columns:
      id: integer primary key
      a_id: integer
    foreign-keys:
      a: { table: a }
