tables:
  customers:
    columns:
      customer_id: serial primary key
      customer_code: varchar(6) unique not null
      customer_name: varchar(30) not null
  vendors:
    columns:
      vendor_id: serial primary key
      vendor_code: varchar(6) unique not null
      vendor_name: varchar(30) not null
