// Generated by GenLogic - DO NOT EDIT
// This file describes the actual database structure after GenLogic processing
// Source: /home/ken/hacking/projects/genlogic/tests/06-behavior/sync-fk-change/schema.yaml
// Database: genlogic_test_cli
// Generated: 2025-11-06T18:38:11.229Z

export const schema = {
  "_metadata": {
    "generated_at": "2025-11-06T18:38:11.228Z",
    "source_schema": "/home/ken/hacking/projects/genlogic/tests/06-behavior/sync-fk-change/schema.yaml",
    "database": "genlogic_test_cli",
    "genlogic_version": "1.0.0",
    "note": "This describes the ACTUAL database structure after GenLogic processing"
  },
  "tables": {
    "categories": {
      "_table_info": {
        "has_automations": false,
        "foreign_keys": 0
      },
      "columns": {
        "id": {
          "type": "integer",
          "primary_key": true,
          "nullable": false,
          "controlled_by": "client application"
        },
        "name": {
          "type": "varchar",
          "size": 100,
          "nullable": true,
          "controlled_by": "client application"
        },
        "tax_rate": {
          "type": "numeric",
          "size": 5,
          "decimal": 2,
          "nullable": true,
          "controlled_by": "client application"
        }
      }
    },
    "products": {
      "_table_info": {
        "has_triggers": true,
        "has_automations": true,
        "foreign_keys": 1
      },
      "columns": {
        "id": {
          "type": "integer",
          "primary_key": true,
          "nullable": false,
          "controlled_by": "client application"
        },
        "category_id": {
          "type": "integer",
          "nullable": true,
          "controlled_by": "client application"
        },
        "name": {
          "type": "varchar",
          "size": 100,
          "nullable": true,
          "controlled_by": "client application"
        },
        "category_tax": {
          "type": "numeric",
          "size": 5,
          "decimal": 2,
          "nullable": true,
          "controlled_by": "database server",
          "formula": "SYNC(categories.tax_rate)",
          "managed_by": {
            "type": "trigger_aggregation",
            "automation_type": "SYNC",
            "source_table": "categories",
            "source_column": "tax_rate",
            "trigger_name": "categories_before_update_genlogic",
            "cascade_path": "categories -> products.category",
            "update_strategy": "on_parent_change",
            "note": "Syncs with categories.tax_rate (updated when parent changes)"
          }
        },
        "category": {
          "type": "integer",
          "nullable": true,
          "source": "foreign_key_column",
          "controlled_by": "client application",
          "references": {
            "table": "categories",
            "column": "category",
            "constraint": "category"
          }
        }
      }
    }
  },
  "matching_tables": {},
  "_usage_guide": {
    "insert_pattern": "To insert data, only include columns where controlled_by = \"client application\".\nExample for accounts:\n  INSERT INTO accounts (account, category) VALUES ('Checking', 'Asset');\n\n❌ WRONG - don't set database-controlled columns:\n  INSERT INTO accounts (account, category, debits, balance) VALUES (...);",
    "update_pattern": "To update data, only modify columns where controlled_by = \"client application\".\nExample for accounts:\n  UPDATE accounts SET category = 'Liability' WHERE id = 5;\n\n❌ WRONG - don't update database-controlled columns:\n  UPDATE accounts SET balance = 1000 WHERE id = 5;  -- Will be overwritten!",
    "query_pattern": "All columns are readable. Automated columns are always current - no need to recalculate.\nExample:\n  SELECT account, category, balance FROM accounts WHERE category = 'Asset';\n\nThe balance is ALWAYS up-to-date due to database triggers.",
    "automation_philosophy": "GenLogic implements \"Augmented Normalization\":\n- Write normalized data (accounts, ledger entries)\n- Read denormalized data (balances pre-calculated)\n- Middleware NEVER calculates aggregations or balances\n- Database maintains ALL computed values via triggers\n- Zero middleware business logic = zero bugs"
  }
} as const;
