// Generated by GenLogic - DO NOT EDIT
// This file describes the actual database structure after GenLogic processing
// Source: /home/ken/hacking/projects/genlogic/tests/06-behavior/automations-count-defaults/schema.yaml
// Database: genlogic_test_cli
// Generated: 2025-11-06T18:37:50.339Z

export const schema = {
  "_metadata": {
    "generated_at": "2025-11-06T18:37:50.338Z",
    "source_schema": "/home/ken/hacking/projects/genlogic/tests/06-behavior/automations-count-defaults/schema.yaml",
    "database": "genlogic_test_cli",
    "genlogic_version": "1.0.0",
    "note": "This describes the ACTUAL database structure after GenLogic processing"
  },
  "tables": {
    "categories": {
      "_table_info": {
        "has_triggers": true,
        "has_automations": true,
        "foreign_keys": 0
      },
      "columns": {
        "category_id": {
          "type": "integer",
          "primary_key": true,
          "nullable": false,
          "controlled_by": "database server",
          "formula": "SERIAL"
        },
        "product_count": {
          "type": "integer",
          "nullable": true,
          "controlled_by": "database server",
          "formula": "COUNT(products.product_id)",
          "managed_by": {
            "type": "trigger_aggregation",
            "automation_type": "COUNT",
            "source_table": "products",
            "source_column": "product_id",
            "trigger_name": "products_before_insert_genlogic",
            "aggregation_path": "products.category_fk -> categories",
            "update_strategy": "incremental",
            "note": "Aggregates COUNT from products.product_id"
          }
        }
      }
    },
    "products": {
      "_table_info": {
        "has_automations": false,
        "foreign_keys": 1
      },
      "columns": {
        "product_id": {
          "type": "integer",
          "primary_key": true,
          "nullable": false,
          "controlled_by": "database server",
          "formula": "SERIAL"
        },
        "category_fk": {
          "type": "integer",
          "nullable": true,
          "source": "foreign_key_column",
          "controlled_by": "client application",
          "references": {
            "table": "categories",
            "column": "category_fk",
            "constraint": "category_fk"
          }
        }
      }
    }
  },
  "matching_tables": {},
  "_usage_guide": {
    "insert_pattern": "To insert data, only include columns where controlled_by = \"client application\".\nExample for accounts:\n  INSERT INTO accounts (account, category) VALUES ('Checking', 'Asset');\n\n❌ WRONG - don't set database-controlled columns:\n  INSERT INTO accounts (account, category, debits, balance) VALUES (...);",
    "update_pattern": "To update data, only modify columns where controlled_by = \"client application\".\nExample for accounts:\n  UPDATE accounts SET category = 'Liability' WHERE id = 5;\n\n❌ WRONG - don't update database-controlled columns:\n  UPDATE accounts SET balance = 1000 WHERE id = 5;  -- Will be overwritten!",
    "query_pattern": "All columns are readable. Automated columns are always current - no need to recalculate.\nExample:\n  SELECT account, category, balance FROM accounts WHERE category = 'Asset';\n\nThe balance is ALWAYS up-to-date due to database triggers.",
    "automation_philosophy": "GenLogic implements \"Augmented Normalization\":\n- Write normalized data (accounts, ledger entries)\n- Read denormalized data (balances pre-calculated)\n- Middleware NEVER calculates aggregations or balances\n- Database maintains ALL computed values via triggers\n- Zero middleware business logic = zero bugs"
  }
} as const;
