// Generated by GenLogic - DO NOT EDIT
// This file describes the actual database structure after GenLogic processing
// Source: /home/ken/hacking/projects/genlogic/tests/06-behavior/singleton-aggregation/schema.yaml
// Database: genlogic_test_cli
// Generated: 2025-11-06T18:38:07.520Z

export const schema = {
  "_metadata": {
    "generated_at": "2025-11-06T18:38:07.519Z",
    "source_schema": "/home/ken/hacking/projects/genlogic/tests/06-behavior/singleton-aggregation/schema.yaml",
    "database": "genlogic_test_cli",
    "genlogic_version": "1.0.0",
    "note": "This describes the ACTUAL database structure after GenLogic processing"
  },
  "tables": {
    "global_totals": {
      "_table_info": {
        "has_triggers": true,
        "has_automations": true,
        "foreign_keys": 0
      },
      "columns": {
        "id": {
          "type": "integer",
          "primary_key": true,
          "nullable": false,
          "controlled_by": "client application"
        },
        "total_sales": {
          "type": "numeric",
          "size": 10,
          "decimal": 2,
          "nullable": true,
          "controlled_by": "database server",
          "formula": "SUM(sales.amount)",
          "managed_by": {
            "type": "trigger_aggregation",
            "automation_type": "SUM",
            "source_table": "sales",
            "source_column": "amount",
            "trigger_name": "sales_before_insert_genlogic",
            "aggregation_path": "sales.global_totals -> global_totals",
            "update_strategy": "incremental",
            "note": "Aggregates SUM from sales.amount"
          }
        },
        "sale_count": {
          "type": "integer",
          "nullable": true,
          "controlled_by": "database server",
          "formula": "COUNT(sales.id)",
          "managed_by": {
            "type": "trigger_aggregation",
            "automation_type": "COUNT",
            "source_table": "sales",
            "source_column": "id",
            "trigger_name": "sales_before_insert_genlogic",
            "aggregation_path": "sales.global_totals -> global_totals",
            "update_strategy": "incremental",
            "note": "Aggregates COUNT from sales.id"
          }
        }
      }
    },
    "sales": {
      "_table_info": {
        "has_automations": false,
        "foreign_keys": 1
      },
      "columns": {
        "id": {
          "type": "integer",
          "primary_key": true,
          "nullable": false,
          "controlled_by": "database server",
          "formula": "SERIAL"
        },
        "global_totals_id": {
          "type": "integer",
          "nullable": true,
          "controlled_by": "client application"
        },
        "amount": {
          "type": "numeric",
          "size": 10,
          "decimal": 2,
          "nullable": true,
          "controlled_by": "client application"
        },
        "sale_date": {
          "type": "date",
          "nullable": true,
          "controlled_by": "client application"
        },
        "global_totals": {
          "type": "integer",
          "nullable": true,
          "source": "foreign_key_column",
          "controlled_by": "client application",
          "references": {
            "table": "global_totals",
            "column": "global_totals",
            "constraint": "global_totals"
          }
        }
      }
    }
  },
  "matching_tables": {},
  "_usage_guide": {
    "insert_pattern": "To insert data, only include columns where controlled_by = \"client application\".\nExample for accounts:\n  INSERT INTO accounts (account, category) VALUES ('Checking', 'Asset');\n\n❌ WRONG - don't set database-controlled columns:\n  INSERT INTO accounts (account, category, debits, balance) VALUES (...);",
    "update_pattern": "To update data, only modify columns where controlled_by = \"client application\".\nExample for accounts:\n  UPDATE accounts SET category = 'Liability' WHERE id = 5;\n\n❌ WRONG - don't update database-controlled columns:\n  UPDATE accounts SET balance = 1000 WHERE id = 5;  -- Will be overwritten!",
    "query_pattern": "All columns are readable. Automated columns are always current - no need to recalculate.\nExample:\n  SELECT account, category, balance FROM accounts WHERE category = 'Asset';\n\nThe balance is ALWAYS up-to-date due to database triggers.",
    "automation_philosophy": "GenLogic implements \"Augmented Normalization\":\n- Write normalized data (accounts, ledger entries)\n- Read denormalized data (balances pre-calculated)\n- Middleware NEVER calculates aggregations or balances\n- Database maintains ALL computed values via triggers\n- Zero middleware business logic = zero bugs"
  }
} as const;
