// Generated by GenLogic - DO NOT EDIT
// This file describes the actual database structure after GenLogic processing
// Source: /home/ken/hacking/genlogic/tests/behavior/automations-multiple/schema.yaml
// Database: genlogic_test_cli
// Generated: 2025-10-14T20:25:15.583Z

export const schema = {
  "_metadata": {
    "generated_at": "2025-10-14T20:25:15.582Z",
    "source_schema": "/home/ken/hacking/genlogic/tests/behavior/automations-multiple/schema.yaml",
    "database": "genlogic_test_cli",
    "genlogic_version": "1.0.0",
    "note": "This describes the ACTUAL database structure after GenLogic processing",
    "warning": "⚠️  DO NOT implement automations in middleware - they run in the database!"
  },
  "tables": {
    "accounts": {
      "_table_info": {
        "has_triggers": true,
        "has_automations": true,
        "foreign_keys": 0
      },
      "columns": {
        "id": {
          "type": "integer",
          "primary_key": true,
          "expect_null_on_read": false,
          "can_write_null": false,
          "writable": "always",
          "insert_behavior": "required",
          "update_behavior": "immutable",
          "note": "Application must provide this value, cannot change after insert"
        },
        "name": {
          "type": "varchar",
          "size": 50,
          "expect_null_on_read": true,
          "can_write_null": true,
          "writable": "always",
          "insert_behavior": "optional",
          "update_behavior": "allowed",
          "note": "Application controls this value"
        },
        "total_amount": {
          "type": "numeric",
          "size": 10,
          "decimal": 2,
          "expect_null_on_read": true,
          "can_write_null": false,
          "writable": "never",
          "reason": "database_automation",
          "managed_by": {
            "type": "trigger_aggregation"
          },
          "insert_behavior": "omit",
          "update_behavior": "forbidden",
          "query_note": "Always reflects current state via triggers",
          "warning": "⚠️  AUTOMATED IN DATABASE - DO NOT SET IN APPLICATION"
        },
        "transaction_count": {
          "type": "integer",
          "expect_null_on_read": true,
          "can_write_null": false,
          "writable": "never",
          "reason": "database_automation",
          "managed_by": {
            "type": "trigger_aggregation"
          },
          "insert_behavior": "omit",
          "update_behavior": "forbidden",
          "query_note": "Always reflects current state via triggers",
          "warning": "⚠️  AUTOMATED IN DATABASE - DO NOT SET IN APPLICATION"
        },
        "max_transaction": {
          "type": "numeric",
          "size": 10,
          "decimal": 2,
          "expect_null_on_read": true,
          "can_write_null": false,
          "writable": "never",
          "reason": "database_automation",
          "managed_by": {
            "type": "trigger_aggregation"
          },
          "insert_behavior": "omit",
          "update_behavior": "forbidden",
          "query_note": "Always reflects current state via triggers",
          "warning": "⚠️  AUTOMATED IN DATABASE - DO NOT SET IN APPLICATION"
        }
      }
    },
    "transactions": {
      "_table_info": {
        "has_automations": false,
        "foreign_keys": 1
      },
      "columns": {
        "id": {
          "type": "integer",
          "primary_key": true,
          "expect_null_on_read": false,
          "can_write_null": false,
          "writable": "always",
          "insert_behavior": "required",
          "update_behavior": "immutable",
          "note": "Application must provide this value, cannot change after insert"
        },
        "account_id": {
          "type": "integer",
          "expect_null_on_read": true,
          "can_write_null": true,
          "writable": "always",
          "insert_behavior": "optional",
          "update_behavior": "allowed",
          "note": "Application controls this value"
        },
        "amount": {
          "type": "numeric",
          "size": 10,
          "decimal": 2,
          "expect_null_on_read": true,
          "can_write_null": true,
          "writable": "always",
          "insert_behavior": "optional",
          "update_behavior": "allowed",
          "note": "Application controls this value"
        },
        "account": {
          "type": "integer",
          "expect_null_on_read": true,
          "can_write_null": true,
          "writable": "always",
          "source": "foreign_key_column",
          "references": {
            "table": "accounts",
            "column": "account",
            "constraint": "account"
          },
          "insert_behavior": "optional",
          "update_behavior": "allowed",
          "note": "Application controls this value to establish relationships"
        }
      }
    }
  },
  "matching_tables": {},
  "_usage_guide": {
    "insert_pattern": "To insert data, only include columns where writable=always and insert_behavior != omit.\nExample for accounts:\n  INSERT INTO accounts (account, category) VALUES ('Checking', 'Asset');\n\n❌ WRONG - don't set automated columns:\n  INSERT INTO accounts (account, category, debits, balance) VALUES (...);",
    "update_pattern": "To update data, only modify columns where writable=always and update_behavior=allowed.\nExample for accounts:\n  UPDATE accounts SET category = 'Liability' WHERE id = 5;\n\n❌ WRONG - don't update automated columns:\n  UPDATE accounts SET balance = 1000 WHERE id = 5;  -- Will be overwritten!",
    "query_pattern": "All columns are readable. Automated columns are always current - no need to recalculate.\nExample:\n  SELECT account, category, balance FROM accounts WHERE category = 'Asset';\n\nThe balance is ALWAYS up-to-date due to database triggers.",
    "automation_philosophy": "GenLogic implements \"Augmented Normalization\":\n- Write normalized data (accounts, ledger entries)\n- Read denormalized data (balances pre-calculated)\n- Middleware NEVER calculates aggregations or balances\n- Database maintains ALL computed values via triggers\n- Zero middleware business logic = zero bugs"
  }
} as const;
