// Generated by GenLogic - DO NOT EDIT
// This file describes the actual database structure after GenLogic processing
// Source: /home/ken/hacking/genlogic/tests/04-schema-features/pattern-matching-tables/schema.yaml
// Database: genlogic_test_cli
// Generated: 2025-10-15T13:30:31.974Z

export const schema = {
  "_metadata": {
    "generated_at": "2025-10-15T13:30:31.973Z",
    "source_schema": "/home/ken/hacking/genlogic/tests/04-schema-features/pattern-matching-tables/schema.yaml",
    "database": "genlogic_test_cli",
    "genlogic_version": "1.0.0",
    "note": "This describes the ACTUAL database structure after GenLogic processing",
    "warning": "⚠️  DO NOT implement automations in middleware - they run in the database!"
  },
  "tables": {},
  "matching_tables": {
    "expense_rules": {
      "_table_info": {
        "type": "pattern_matching_table",
        "description": "Auto-generated pattern matching table with fixed structure for categorization",
        "has_stored_procedures": true,
        "writable": "always",
        "note": "This table uses fixed structure: id, string_match, result_column, range_low_bound, range_high_bound"
      },
      "columns": {
        "id": {
          "type": "SERIAL",
          "primary_key": true,
          "writable": "never",
          "reason": "auto_increment_sequence",
          "insert_behavior": "omit",
          "update_behavior": "immutable",
          "note": "Auto-generated primary key"
        },
        "string_match": {
          "type": "VARCHAR(200)",
          "writable": "always",
          "insert_behavior": "required",
          "update_behavior": "allowed",
          "note": "Pattern with SQL LIKE wildcards (%, _) to match against descriptions",
          "example": "%starbucks%"
        },
        "category": {
          "type": "VARCHAR(100)",
          "writable": "always",
          "insert_behavior": "required",
          "update_behavior": "allowed",
          "note": "The categorization result value to return when this rule matches",
          "example": "Coffee"
        },
        "range_low_bound": {
          "type": "NUMERIC(10,2)",
          "writable": "always",
          "insert_behavior": "optional",
          "update_behavior": "allowed",
          "nullable": true,
          "note": "Minimum numeric value constraint (NULL = no lower bound)",
          "example": "10.00"
        },
        "range_high_bound": {
          "type": "NUMERIC(10,2)",
          "writable": "always",
          "insert_behavior": "optional",
          "update_behavior": "allowed",
          "nullable": true,
          "note": "Maximum numeric value constraint (NULL = no upper bound)",
          "example": "50.00"
        }
      },
      "stored_procedures": {
        "match_best": {
          "name": "expense_rules_match_best",
          "signature": "(p_inputs JSONB)",
          "returns": "TABLE(input_id INTEGER, matched_id INTEGER, string_match VARCHAR, result_value VARCHAR, matched_column_count INTEGER, pattern_length INTEGER)",
          "description": "Returns the best (most specific) match for each input based on matched column count and pattern length",
          "usage": "-- Match multiple inputs and get best match for each\nSELECT * FROM expense_rules_match_best(\n  '[{\"id\": 1, \"description\": \"STARBUCKS PURCHASE\", \"amount\": 5.50},\n    {\"id\": 2, \"description\": \"GROCERY STORE\", \"amount\": 45.00}]'::jsonb\n);",
          "input_format": {
            "required_fields": [
              "id (integer)",
              "description (text)"
            ],
            "optional_fields": [
              "amount (numeric)"
            ],
            "example": "[{\"id\": 1, \"description\": \"Transaction text\", \"amount\": 25.50}]"
          },
          "ranking_logic": {
            "primary": "matched_column_count (higher is better)",
            "tiebreaker": "pattern_length (longer is more specific)",
            "explanation": "Pattern match = 1 point, range_low_bound match = +1 point, range_high_bound match = +1 point"
          }
        },
        "match_all": {
          "name": "expense_rules_match_all",
          "signature": "(p_inputs JSONB)",
          "returns": "TABLE(input_id INTEGER, matched_id INTEGER, string_match VARCHAR, result_value VARCHAR, matched_column_count INTEGER, pattern_length INTEGER, match_rank INTEGER)",
          "description": "Returns ALL matches for each input, ranked by specificity (match_rank = 1 is best)",
          "usage": "-- Get all matching rules for review\nSELECT * FROM expense_rules_match_all(\n  '[{\"id\": 1, \"description\": \"COFFEE SHOP\", \"amount\": 15.00}]'::jsonb\n)\nORDER BY input_id, match_rank;",
          "use_case": "Useful for debugging rules, showing users alternatives, or implementing custom selection logic"
        }
      },
      "usage_examples": {
        "insert_rules": {
          "simple_pattern": "-- Pattern-only rule (matches any amount)\nINSERT INTO expense_rules (string_match, category) VALUES\n  ('%coffee%', 'Beverage');",
          "with_range": "-- Pattern with amount range\nINSERT INTO expense_rules (string_match, category, range_low_bound, range_high_bound) VALUES\n  ('%restaurant%', 'Dining - Expensive', 50.00, NULL),\n  ('%restaurant%', 'Dining - Moderate', 15.00, 50.00),\n  ('%restaurant%', 'Dining - Cheap', NULL, 15.00);",
          "exact_amount": "-- Exact amount match (both bounds equal)\nINSERT INTO expense_rules (string_match, category, range_low_bound, range_high_bound) VALUES\n  ('%streaming%', 'Premium Subscription', 14.99, 14.99);"
        },
        "call_functions": {
          "match_best": "-- Categorize new transactions\nSELECT \n  t.transaction_id,\n  t.description,\n  t.amount,\n  m.result_value AS category\nFROM transactions t\nCROSS JOIN LATERAL (\n  SELECT result_value \n  FROM expense_rules_match_best(\n    jsonb_build_array(jsonb_build_object(\n      'id', t.transaction_id,\n      'description', t.description,\n      'amount', t.amount\n    ))\n  )\n) m\nWHERE t.category IS NULL;",
          "match_all": "-- Review all matching rules for debugging\nSELECT \n  input_id,\n  match_rank,\n  string_match,\n  result_value,\n  matched_column_count\nFROM expense_rules_match_all(\n  '[{\"id\": 1, \"description\": \"COFFEE SHOP PURCHASE\", \"amount\": 7.50}]'::jsonb\n)\nORDER BY match_rank;"
        }
      },
      "specificity_examples": {
        "description": "Rules are ranked by specificity: more matching constraints = higher rank",
        "examples": [
          {
            "rule": "%coffee% with NO range constraints",
            "matched_column_count": 1,
            "specificity": "low"
          },
          {
            "rule": "%coffee% with range_low_bound = 5.00",
            "matched_column_count": 2,
            "specificity": "medium"
          },
          {
            "rule": "%coffee% with range_low_bound = 5.00 AND range_high_bound = 10.00",
            "matched_column_count": 3,
            "specificity": "high"
          }
        ],
        "tiebreaker": "If matched_column_count is equal, longer patterns win (more specific text match)"
      }
    }
  },
  "_usage_guide": {
    "insert_pattern": "To insert data, only include columns where writable=always and insert_behavior != omit.\nExample for accounts:\n  INSERT INTO accounts (account, category) VALUES ('Checking', 'Asset');\n\n❌ WRONG - don't set automated columns:\n  INSERT INTO accounts (account, category, debits, balance) VALUES (...);",
    "update_pattern": "To update data, only modify columns where writable=always and update_behavior=allowed.\nExample for accounts:\n  UPDATE accounts SET category = 'Liability' WHERE id = 5;\n\n❌ WRONG - don't update automated columns:\n  UPDATE accounts SET balance = 1000 WHERE id = 5;  -- Will be overwritten!",
    "query_pattern": "All columns are readable. Automated columns are always current - no need to recalculate.\nExample:\n  SELECT account, category, balance FROM accounts WHERE category = 'Asset';\n\nThe balance is ALWAYS up-to-date due to database triggers.",
    "automation_philosophy": "GenLogic implements \"Augmented Normalization\":\n- Write normalized data (accounts, ledger entries)\n- Read denormalized data (balances pre-calculated)\n- Middleware NEVER calculates aggregations or balances\n- Database maintains ALL computed values via triggers\n- Zero middleware business logic = zero bugs"
  }
} as const;
