// Generated by GenLogic - DO NOT EDIT
// This file describes the actual database structure after GenLogic processing
// Source: /home/ken/hacking/projects/genlogic/tests/05-schema-features/label-and-format/schema.yaml
// Database: genlogic_test_cli
// Generated: 2025-11-06T18:37:39.201Z

export const schema = {
  "_metadata": {
    "generated_at": "2025-11-06T18:37:39.199Z",
    "source_schema": "/home/ken/hacking/projects/genlogic/tests/05-schema-features/label-and-format/schema.yaml",
    "database": "genlogic_test_cli",
    "genlogic_version": "1.0.0",
    "note": "This describes the ACTUAL database structure after GenLogic processing"
  },
  "tables": {
    "users": {
      "_table_info": {
        "has_automations": false,
        "foreign_keys": 0
      },
      "columns": {
        "id": {
          "type": "integer",
          "label": "User ID",
          "format": "id",
          "primary_key": true,
          "nullable": false,
          "controlled_by": "database server",
          "formula": "SERIAL"
        },
        "name": {
          "type": "varchar",
          "size": 100,
          "nullable": true,
          "controlled_by": "client application"
        },
        "email": {
          "type": "varchar",
          "label": "Email Address",
          "format": "email",
          "size": 255,
          "nullable": true,
          "controlled_by": "client application"
        }
      }
    },
    "accounts": {
      "_table_info": {
        "has_automations": false,
        "foreign_keys": 1
      },
      "columns": {
        "id": {
          "type": "integer",
          "label": "Account ID",
          "format": "id",
          "primary_key": true,
          "nullable": false,
          "controlled_by": "database server",
          "formula": "SERIAL"
        },
        "balance": {
          "type": "numeric",
          "label": "Account Balance",
          "format": "currency",
          "size": 10,
          "decimal": 2,
          "nullable": true,
          "controlled_by": "client application"
        },
        "user_id": {
          "type": "integer",
          "label": "User ID",
          "format": "id",
          "nullable": true,
          "source": "foreign_key_column",
          "controlled_by": "client application",
          "references": {
            "table": "users",
            "column": "user_id",
            "constraint": "user_id"
          }
        }
      }
    },
    "transactions": {
      "_table_info": {
        "has_automations": false,
        "foreign_keys": 2
      },
      "columns": {
        "id": {
          "type": "integer",
          "label": "Transaction ID",
          "format": "id",
          "primary_key": true,
          "nullable": false,
          "controlled_by": "database server",
          "formula": "SERIAL"
        },
        "amount": {
          "type": "numeric",
          "label": "Transaction Amount",
          "format": "currency",
          "size": 10,
          "decimal": 2,
          "nullable": true,
          "controlled_by": "client application"
        },
        "transaction_date": {
          "type": "timestamp",
          "label": "Date",
          "format": "datetime",
          "nullable": true,
          "controlled_by": "client application"
        },
        "account_id": {
          "type": "integer",
          "label": "Account ID",
          "format": "id",
          "nullable": true,
          "source": "foreign_key_column",
          "controlled_by": "client application",
          "references": {
            "table": "accounts",
            "column": "account_id",
            "constraint": "account_id"
          }
        },
        "user_id": {
          "type": "integer",
          "label": "User ID",
          "format": "id",
          "nullable": true,
          "source": "foreign_key_column",
          "controlled_by": "client application",
          "references": {
            "table": "users",
            "column": "user_id",
            "constraint": "user_id"
          }
        }
      }
    },
    "ledger": {
      "_table_info": {
        "has_triggers": true,
        "has_automations": true,
        "foreign_keys": 2
      },
      "columns": {
        "id": {
          "type": "integer",
          "label": "Ledger ID",
          "format": "id",
          "primary_key": true,
          "nullable": false,
          "controlled_by": "database server",
          "formula": "SERIAL"
        },
        "snapshot_amount": {
          "type": "numeric",
          "label": "Transaction Amount",
          "format": "currency",
          "size": 10,
          "decimal": 2,
          "nullable": true,
          "controlled_by": "database server",
          "formula": "SNAPSHOT(transactions.amount)",
          "managed_by": {
            "type": "trigger_aggregation",
            "automation_type": "SNAPSHOT",
            "source_table": "transactions",
            "source_column": "amount",
            "trigger_name": "ledger_before_insert_genlogic",
            "cascade_path": "transactions -> ledger.transaction_id",
            "update_strategy": "on_insert_only",
            "note": "Snapshot from transactions.amount (captured on INSERT only)"
          }
        },
        "synced_balance": {
          "type": "numeric",
          "label": "Account Balance",
          "format": "currency",
          "size": 10,
          "decimal": 2,
          "nullable": true,
          "controlled_by": "database server",
          "formula": "SYNC(accounts.balance)",
          "managed_by": {
            "type": "trigger_aggregation",
            "automation_type": "SYNC",
            "source_table": "accounts",
            "source_column": "balance",
            "trigger_name": "accounts_before_update_genlogic",
            "cascade_path": "accounts -> ledger.account_id",
            "update_strategy": "on_parent_change",
            "note": "Syncs with accounts.balance (updated when parent changes)"
          }
        },
        "transaction_id": {
          "type": "integer",
          "label": "Transaction ID",
          "format": "id",
          "nullable": true,
          "source": "foreign_key_column",
          "controlled_by": "client application",
          "references": {
            "table": "transactions",
            "column": "transaction_id",
            "constraint": "transaction_id"
          }
        },
        "account_id": {
          "type": "integer",
          "label": "Account ID",
          "format": "id",
          "nullable": true,
          "source": "foreign_key_column",
          "controlled_by": "client application",
          "references": {
            "table": "accounts",
            "column": "account_id",
            "constraint": "account_id"
          }
        }
      }
    }
  },
  "matching_tables": {},
  "_usage_guide": {
    "insert_pattern": "To insert data, only include columns where controlled_by = \"client application\".\nExample for accounts:\n  INSERT INTO accounts (account, category) VALUES ('Checking', 'Asset');\n\n❌ WRONG - don't set database-controlled columns:\n  INSERT INTO accounts (account, category, debits, balance) VALUES (...);",
    "update_pattern": "To update data, only modify columns where controlled_by = \"client application\".\nExample for accounts:\n  UPDATE accounts SET category = 'Liability' WHERE id = 5;\n\n❌ WRONG - don't update database-controlled columns:\n  UPDATE accounts SET balance = 1000 WHERE id = 5;  -- Will be overwritten!",
    "query_pattern": "All columns are readable. Automated columns are always current - no need to recalculate.\nExample:\n  SELECT account, category, balance FROM accounts WHERE category = 'Asset';\n\nThe balance is ALWAYS up-to-date due to database triggers.",
    "automation_philosophy": "GenLogic implements \"Augmented Normalization\":\n- Write normalized data (accounts, ledger entries)\n- Read denormalized data (balances pre-calculated)\n- Middleware NEVER calculates aggregations or balances\n- Database maintains ALL computed values via triggers\n- Zero middleware business logic = zero bugs"
  }
} as const;
