tables:
  order_headers:
    columns:
      order_id: integer primary key
      order_year: integer primary key

  order_lines:
    foreign-keys:
      parent:
        table: order_headers
        prefix: parent_
    columns:
      line_id: serial primary key
      # Should auto-create: parent_order_id and parent_order_year
