// Generated by GenLogic - DO NOT EDIT
// This file describes the actual database structure after GenLogic processing
// Source: /home/ken/hacking/projects/genlogic/tests/06-behavior/spread-copy-columns/schema.yaml
// Database: genlogic_test_cli
// Generated: 2025-11-06T18:38:08.339Z

export const schema = {
  "_metadata": {
    "generated_at": "2025-11-06T18:38:08.338Z",
    "source_schema": "/home/ken/hacking/projects/genlogic/tests/06-behavior/spread-copy-columns/schema.yaml",
    "database": "genlogic_test_cli",
    "genlogic_version": "1.0.0",
    "note": "This describes the ACTUAL database structure after GenLogic processing"
  },
  "tables": {
    "projects": {
      "_table_info": {
        "has_automations": false,
        "foreign_keys": 0
      },
      "columns": {
        "project_id": {
          "type": "integer",
          "primary_key": true,
          "nullable": false,
          "controlled_by": "database server",
          "formula": "SERIAL"
        },
        "project_name": {
          "type": "varchar",
          "size": 100,
          "nullable": true,
          "controlled_by": "client application"
        },
        "default_assignee": {
          "type": "varchar",
          "size": 50,
          "nullable": true,
          "controlled_by": "client application"
        },
        "start_date": {
          "type": "date",
          "nullable": true,
          "controlled_by": "client application"
        },
        "end_date": {
          "type": "date",
          "nullable": true,
          "controlled_by": "client application"
        },
        "frequency": {
          "type": "varchar",
          "size": 20,
          "nullable": true,
          "controlled_by": "client application"
        }
      }
    },
    "tasks": {
      "_table_info": {
        "has_automations": false,
        "foreign_keys": 1
      },
      "columns": {
        "task_id": {
          "type": "integer",
          "primary_key": true,
          "nullable": false,
          "controlled_by": "database server",
          "formula": "SERIAL"
        },
        "task_date": {
          "type": "date",
          "nullable": true,
          "controlled_by": "client application"
        },
        "task_prefix": {
          "type": "varchar",
          "size": 100,
          "nullable": true,
          "controlled_by": "client application"
        },
        "assignee": {
          "type": "varchar",
          "size": 50,
          "nullable": true,
          "controlled_by": "client application"
        },
        "project_id": {
          "type": "integer",
          "nullable": true,
          "source": "foreign_key_column",
          "controlled_by": "client application",
          "references": {
            "table": "projects",
            "column": "project_id",
            "constraint": "project_id"
          }
        }
      }
    }
  },
  "matching_tables": {},
  "_usage_guide": {
    "insert_pattern": "To insert data, only include columns where controlled_by = \"client application\".\nExample for accounts:\n  INSERT INTO accounts (account, category) VALUES ('Checking', 'Asset');\n\n❌ WRONG - don't set database-controlled columns:\n  INSERT INTO accounts (account, category, debits, balance) VALUES (...);",
    "update_pattern": "To update data, only modify columns where controlled_by = \"client application\".\nExample for accounts:\n  UPDATE accounts SET category = 'Liability' WHERE id = 5;\n\n❌ WRONG - don't update database-controlled columns:\n  UPDATE accounts SET balance = 1000 WHERE id = 5;  -- Will be overwritten!",
    "query_pattern": "All columns are readable. Automated columns are always current - no need to recalculate.\nExample:\n  SELECT account, category, balance FROM accounts WHERE category = 'Asset';\n\nThe balance is ALWAYS up-to-date due to database triggers.",
    "automation_philosophy": "GenLogic implements \"Augmented Normalization\":\n- Write normalized data (accounts, ledger entries)\n- Read denormalized data (balances pre-calculated)\n- Middleware NEVER calculates aggregations or balances\n- Database maintains ALL computed values via triggers\n- Zero middleware business logic = zero bugs"
  }
} as const;
