tables:
  devices:
    columns:
      id: integer primary key
      name: varchar(50)
      last_reading:
        definition: numeric(10,2)
        automation: LAST_VALUE @readings.value

  readings:
    columns:
      id: integer primary key
      device_id: integer
      value: numeric(10,2)
      timestamp: timestamp
    foreign-keys:
      device: { table: devices }
