// Generated by GenLogic - DO NOT EDIT
// This file describes the actual database structure after GenLogic processing
// Source: /home/ken/hacking/projects/genlogic/tests/05-schema-features/column-types/schema.yaml
// Database: genlogic_test_cli
// Generated: 2025-11-06T18:37:25.741Z

export const schema = {
  "_metadata": {
    "generated_at": "2025-11-06T18:37:25.740Z",
    "source_schema": "/home/ken/hacking/projects/genlogic/tests/05-schema-features/column-types/schema.yaml",
    "database": "genlogic_test_cli",
    "genlogic_version": "1.0.0",
    "note": "This describes the ACTUAL database structure after GenLogic processing"
  },
  "tables": {
    "type_showcase": {
      "_table_info": {
        "has_automations": false,
        "foreign_keys": 0
      },
      "columns": {
        "id": {
          "type": "integer",
          "primary_key": true,
          "nullable": false,
          "controlled_by": "database server",
          "formula": "SERIAL"
        },
        "big_id": {
          "type": "bigint",
          "nullable": false,
          "controlled_by": "database server",
          "formula": "SERIAL"
        },
        "small_id": {
          "type": "smallint",
          "nullable": false,
          "controlled_by": "database server",
          "formula": "SERIAL"
        },
        "age": {
          "type": "integer",
          "nullable": true,
          "controlled_by": "client application"
        },
        "stock_count": {
          "type": "bigint",
          "nullable": true,
          "controlled_by": "client application"
        },
        "priority": {
          "type": "smallint",
          "nullable": true,
          "controlled_by": "client application"
        },
        "name": {
          "type": "varchar",
          "size": 100,
          "nullable": true,
          "controlled_by": "client application"
        },
        "email": {
          "type": "varchar",
          "size": 255,
          "unique": true,
          "nullable": true,
          "controlled_by": "client application"
        },
        "code": {
          "type": "char",
          "size": 10,
          "nullable": true,
          "controlled_by": "client application"
        },
        "bio": {
          "type": "text",
          "nullable": true,
          "controlled_by": "client application"
        },
        "salary": {
          "type": "numeric",
          "size": 10,
          "decimal": 2,
          "nullable": true,
          "controlled_by": "client application"
        },
        "price": {
          "type": "decimal",
          "size": 8,
          "decimal": 3,
          "nullable": true,
          "controlled_by": "client application"
        },
        "unlimited_precision": {
          "type": "numeric",
          "nullable": true,
          "controlled_by": "client application"
        },
        "ratio": {
          "type": "real",
          "nullable": true,
          "controlled_by": "client application"
        },
        "precise_ratio": {
          "type": "double_precision",
          "nullable": true,
          "controlled_by": "client application"
        },
        "is_active": {
          "type": "boolean",
          "nullable": true,
          "controlled_by": "client application"
        },
        "birth_date": {
          "type": "date",
          "nullable": true,
          "controlled_by": "client application"
        },
        "created_at": {
          "type": "timestamp",
          "nullable": true,
          "controlled_by": "client application"
        },
        "updated_at": {
          "type": "timestamptz",
          "nullable": true,
          "controlled_by": "client application"
        },
        "external_id": {
          "type": "uuid",
          "nullable": true,
          "controlled_by": "client application"
        },
        "bit_flags": {
          "type": "bit",
          "size": 8,
          "nullable": true,
          "controlled_by": "client application"
        },
        "settings": {
          "type": "json",
          "nullable": true,
          "controlled_by": "client application"
        },
        "metadata": {
          "type": "jsonb",
          "nullable": true,
          "controlled_by": "client application"
        }
      }
    }
  },
  "matching_tables": {},
  "_usage_guide": {
    "insert_pattern": "To insert data, only include columns where controlled_by = \"client application\".\nExample for accounts:\n  INSERT INTO accounts (account, category) VALUES ('Checking', 'Asset');\n\n❌ WRONG - don't set database-controlled columns:\n  INSERT INTO accounts (account, category, debits, balance) VALUES (...);",
    "update_pattern": "To update data, only modify columns where controlled_by = \"client application\".\nExample for accounts:\n  UPDATE accounts SET category = 'Liability' WHERE id = 5;\n\n❌ WRONG - don't update database-controlled columns:\n  UPDATE accounts SET balance = 1000 WHERE id = 5;  -- Will be overwritten!",
    "query_pattern": "All columns are readable. Automated columns are always current - no need to recalculate.\nExample:\n  SELECT account, category, balance FROM accounts WHERE category = 'Asset';\n\nThe balance is ALWAYS up-to-date due to database triggers.",
    "automation_philosophy": "GenLogic implements \"Augmented Normalization\":\n- Write normalized data (accounts, ledger entries)\n- Read denormalized data (balances pre-calculated)\n- Middleware NEVER calculates aggregations or balances\n- Database maintains ALL computed values via triggers\n- Zero middleware business logic = zero bugs"
  }
} as const;
