// Generated by GenLogic - DO NOT EDIT
// This file describes the actual database structure after GenLogic processing
// Source: /home/ken/hacking/projects/genlogic/tests/05-schema-features/additive-aggregation-backfill-all-types/schema.yaml
// Database: genlogic_test_cli
// Generated: 2025-11-06T18:37:21.026Z

export const schema = {
  "_metadata": {
    "generated_at": "2025-11-06T18:37:21.025Z",
    "source_schema": "/home/ken/hacking/projects/genlogic/tests/05-schema-features/additive-aggregation-backfill-all-types/schema.yaml",
    "database": "genlogic_test_cli",
    "genlogic_version": "1.0.0",
    "note": "This describes the ACTUAL database structure after GenLogic processing"
  },
  "tables": {
    "orders": {
      "_table_info": {
        "has_triggers": true,
        "has_automations": true,
        "foreign_keys": 0
      },
      "columns": {
        "id": {
          "type": "integer",
          "primary_key": true,
          "nullable": false,
          "controlled_by": "database server",
          "formula": "SERIAL"
        },
        "customer_name": {
          "type": "varchar",
          "size": 100,
          "nullable": true,
          "controlled_by": "client application"
        },
        "total_quantity": {
          "type": "integer",
          "nullable": true,
          "controlled_by": "database server",
          "formula": "SUM(order_items.quantity)",
          "managed_by": {
            "type": "trigger_aggregation",
            "automation_type": "SUM",
            "source_table": "order_items",
            "source_column": "quantity",
            "trigger_name": "order_items_before_insert_genlogic",
            "aggregation_path": "order_items.order -> orders",
            "update_strategy": "incremental",
            "note": "Aggregates SUM from order_items.quantity"
          }
        },
        "item_count": {
          "type": "integer",
          "nullable": true,
          "controlled_by": "database server",
          "formula": "COUNT(order_items.id)",
          "managed_by": {
            "type": "trigger_aggregation",
            "automation_type": "COUNT",
            "source_table": "order_items",
            "source_column": "id",
            "trigger_name": "order_items_before_insert_genlogic",
            "aggregation_path": "order_items.order -> orders",
            "update_strategy": "incremental",
            "note": "Aggregates COUNT from order_items.id"
          }
        },
        "max_price": {
          "type": "numeric",
          "size": 10,
          "decimal": 2,
          "nullable": true,
          "controlled_by": "database server",
          "formula": "MAX(order_items.unit_price)",
          "managed_by": {
            "type": "trigger_aggregation",
            "automation_type": "MAX",
            "source_table": "order_items",
            "source_column": "unit_price",
            "trigger_name": "order_items_before_insert_genlogic",
            "aggregation_path": "order_items.order -> orders",
            "update_strategy": "incremental",
            "note": "Aggregates MAX from order_items.unit_price"
          }
        },
        "min_price": {
          "type": "numeric",
          "size": 10,
          "decimal": 2,
          "nullable": true,
          "controlled_by": "database server",
          "formula": "MIN(order_items.unit_price)",
          "managed_by": {
            "type": "trigger_aggregation",
            "automation_type": "MIN",
            "source_table": "order_items",
            "source_column": "unit_price",
            "trigger_name": "order_items_before_insert_genlogic",
            "aggregation_path": "order_items.order -> orders",
            "update_strategy": "incremental",
            "note": "Aggregates MIN from order_items.unit_price"
          }
        }
      }
    },
    "order_items": {
      "_table_info": {
        "has_automations": false,
        "foreign_keys": 1
      },
      "columns": {
        "id": {
          "type": "integer",
          "primary_key": true,
          "nullable": false,
          "controlled_by": "database server",
          "formula": "SERIAL"
        },
        "order_id": {
          "type": "integer",
          "nullable": true,
          "controlled_by": "client application"
        },
        "unit_price": {
          "type": "numeric",
          "size": 10,
          "decimal": 2,
          "nullable": true,
          "controlled_by": "client application"
        },
        "quantity": {
          "type": "integer",
          "nullable": true,
          "controlled_by": "client application"
        },
        "order": {
          "type": "integer",
          "nullable": true,
          "source": "foreign_key_column",
          "controlled_by": "client application",
          "references": {
            "table": "orders",
            "column": "order",
            "constraint": "order"
          }
        }
      }
    }
  },
  "matching_tables": {},
  "_usage_guide": {
    "insert_pattern": "To insert data, only include columns where controlled_by = \"client application\".\nExample for accounts:\n  INSERT INTO accounts (account, category) VALUES ('Checking', 'Asset');\n\n❌ WRONG - don't set database-controlled columns:\n  INSERT INTO accounts (account, category, debits, balance) VALUES (...);",
    "update_pattern": "To update data, only modify columns where controlled_by = \"client application\".\nExample for accounts:\n  UPDATE accounts SET category = 'Liability' WHERE id = 5;\n\n❌ WRONG - don't update database-controlled columns:\n  UPDATE accounts SET balance = 1000 WHERE id = 5;  -- Will be overwritten!",
    "query_pattern": "All columns are readable. Automated columns are always current - no need to recalculate.\nExample:\n  SELECT account, category, balance FROM accounts WHERE category = 'Asset';\n\nThe balance is ALWAYS up-to-date due to database triggers.",
    "automation_philosophy": "GenLogic implements \"Augmented Normalization\":\n- Write normalized data (accounts, ledger entries)\n- Read denormalized data (balances pre-calculated)\n- Middleware NEVER calculates aggregations or balances\n- Database maintains ALL computed values via triggers\n- Zero middleware business logic = zero bugs"
  }
} as const;
