// Generated by GenLogic - DO NOT EDIT
// This file describes the actual database structure after GenLogic processing
// Source: /home/ken/hacking/projects/genlogic/tests/05-schema-features/indexes-and-constraints/schema.yaml
// Database: genlogic_test_cli
// Generated: 2025-11-06T18:37:38.342Z

export const schema = {
  "_metadata": {
    "generated_at": "2025-11-06T18:37:38.341Z",
    "source_schema": "/home/ken/hacking/projects/genlogic/tests/05-schema-features/indexes-and-constraints/schema.yaml",
    "database": "genlogic_test_cli",
    "genlogic_version": "1.0.0",
    "note": "This describes the ACTUAL database structure after GenLogic processing"
  },
  "tables": {
    "students": {
      "_table_info": {
        "has_automations": false,
        "foreign_keys": 0
      },
      "columns": {
        "student_id": {
          "type": "integer",
          "primary_key": true,
          "nullable": false,
          "controlled_by": "database server",
          "formula": "SERIAL"
        },
        "email": {
          "type": "varchar",
          "size": 100,
          "unique": true,
          "nullable": true,
          "controlled_by": "client application"
        },
        "name": {
          "type": "varchar",
          "size": 100,
          "nullable": true,
          "controlled_by": "client application"
        }
      }
    },
    "courses": {
      "_table_info": {
        "has_automations": false,
        "foreign_keys": 0
      },
      "columns": {
        "course_id": {
          "type": "integer",
          "primary_key": true,
          "nullable": false,
          "controlled_by": "database server",
          "formula": "SERIAL"
        },
        "code": {
          "type": "varchar",
          "size": 10,
          "unique": true,
          "nullable": true,
          "controlled_by": "client application"
        },
        "title": {
          "type": "varchar",
          "size": 100,
          "nullable": true,
          "controlled_by": "client application"
        }
      }
    },
    "enrollments": {
      "_table_info": {
        "has_automations": false,
        "foreign_keys": 2
      },
      "indexes": [
        {
          "columns": [
            "enrollment_date"
          ]
        },
        {
          "columns": [
            "semester",
            "grade"
          ]
        }
      ],
      "unique_constraints": [
        {
          "columns": [
            "student",
            "course",
            "semester"
          ]
        }
      ],
      "columns": {
        "enrollment_id": {
          "type": "integer",
          "primary_key": true,
          "nullable": false,
          "controlled_by": "database server",
          "formula": "SERIAL"
        },
        "semester": {
          "type": "varchar",
          "size": 20,
          "nullable": true,
          "controlled_by": "client application"
        },
        "grade": {
          "type": "varchar",
          "size": 2,
          "nullable": true,
          "controlled_by": "client application"
        },
        "enrollment_date": {
          "type": "date",
          "nullable": true,
          "controlled_by": "client application"
        },
        "student": {
          "type": "integer",
          "nullable": true,
          "source": "foreign_key_column",
          "controlled_by": "client application",
          "references": {
            "table": "students",
            "column": "student",
            "constraint": "student"
          }
        },
        "course": {
          "type": "integer",
          "nullable": true,
          "source": "foreign_key_column",
          "controlled_by": "client application",
          "references": {
            "table": "courses",
            "column": "course",
            "constraint": "course"
          }
        }
      }
    }
  },
  "matching_tables": {},
  "_usage_guide": {
    "insert_pattern": "To insert data, only include columns where controlled_by = \"client application\".\nExample for accounts:\n  INSERT INTO accounts (account, category) VALUES ('Checking', 'Asset');\n\n❌ WRONG - don't set database-controlled columns:\n  INSERT INTO accounts (account, category, debits, balance) VALUES (...);",
    "update_pattern": "To update data, only modify columns where controlled_by = \"client application\".\nExample for accounts:\n  UPDATE accounts SET category = 'Liability' WHERE id = 5;\n\n❌ WRONG - don't update database-controlled columns:\n  UPDATE accounts SET balance = 1000 WHERE id = 5;  -- Will be overwritten!",
    "query_pattern": "All columns are readable. Automated columns are always current - no need to recalculate.\nExample:\n  SELECT account, category, balance FROM accounts WHERE category = 'Asset';\n\nThe balance is ALWAYS up-to-date due to database triggers.",
    "automation_philosophy": "GenLogic implements \"Augmented Normalization\":\n- Write normalized data (accounts, ledger entries)\n- Read denormalized data (balances pre-calculated)\n- Middleware NEVER calculates aggregations or balances\n- Database maintains ALL computed values via triggers\n- Zero middleware business logic = zero bugs"
  }
} as const;
