tables:
  projects:
    columns:
      id:
        definition: serial primary key
      name:
        definition: varchar(100)

  tasks:
    columns:
      id:
        definition: serial primary key
      task_name:
        definition: varchar(100)
    foreign-keys:
      project_id:
        table: projects
        auto-create:
          on: [insert]
          literals:
            # Non-existent child column
            nonexistent_column: "default_value"
